import { useState } from 'react';
import { useBookkeeping } from '../context/BookkeepingContext';
import { AddRounded, CloseRounded, DeleteOutlineRounded, EditRounded, VisibilityRounded } from '@mui/icons-material';
import { IconButton, Tooltip } from '@mui/material';

const empty = { number: '', client: '', dueDate: '', amount: '', status: 'Draft' };
const money = (value) => new Intl.NumberFormat('en-CA', { style: 'currency', currency: 'CAD' }).format(Number(value) || 0);

function receiptMarkup(invoice, businessName) {
  return `<!doctype html><html><head><title>Receipt ${invoice.number}</title><style>
    body{font-family:Arial,sans-serif;color:#172033;max-width:720px;margin:40px auto;padding:24px}
    header{display:flex;justify-content:space-between;border-bottom:3px solid #40189d;padding-bottom:20px}
    h1{color:#40189d;margin:0 0 8px}h2{margin:28px 0 8px}p{color:#68758a}
    .row{display:flex;justify-content:space-between;border-bottom:1px solid #e5e9f0;padding:14px 0}
    .total{font-size:22px;font-weight:700;border-bottom:0}.badge{color:#147f65;font-weight:700}
  </style></head><body><header><div><h1>${businessName}</h1><p>Payment receipt</p></div><div><strong>${invoice.number}</strong><p>${invoice.dueDate || 'No due date'}</p></div></header>
  <h2>Received from</h2><p>${invoice.client}</p><div class="row"><span>Invoice amount</span><strong>${money(invoice.amount)}</strong></div>
  <div class="row"><span>Status</span><span class="badge">${invoice.status}</span></div><div class="row total"><span>Total</span><span>${money(invoice.amount)}</span></div>
  <p>Generated by Ledgerwise. Keep this receipt with your business records.</p></body></html>`;
}

export default function InvoicesPage() {
  const { invoices, settings, addInvoice, updateInvoice, deleteInvoice } = useBookkeeping();
  const [form, setForm] = useState(empty);
  const [editing, setEditing] = useState(null);
  const [selected, setSelected] = useState(null);
  const [invoiceModalOpen, setInvoiceModalOpen] = useState(false);
  const change = (event) => setForm({ ...form, [event.target.name]: event.target.value });
  const resetForm = () => { setEditing(null); setForm(empty); };
  const closeInvoiceModal = () => { setInvoiceModalOpen(false); resetForm(); };
  const submit = (event) => {
    event.preventDefault();
    if (!form.number || !form.client || !form.amount) return;
    if (editing) updateInvoice(editing, form); else addInvoice(form);
    closeInvoiceModal();
  };
  const edit = (invoice) => { setEditing(invoice.id); setForm({ ...invoice }); setInvoiceModalOpen(true); };
  const downloadReceipt = (invoice) => {
    const blob = new Blob([receiptMarkup(invoice, settings.businessName)], { type: 'text/html' });
    const url = URL.createObjectURL(blob); const anchor = document.createElement('a');
    anchor.href = url; anchor.download = `${invoice.number}-receipt.html`; anchor.click(); URL.revokeObjectURL(url);
  };
  const printReceipt = (invoice) => {
    const printWindow = window.open('', '_blank', 'noopener,noreferrer');
    if (!printWindow) return;
    printWindow.document.write(receiptMarkup(invoice, settings.businessName));
    printWindow.document.close(); printWindow.focus(); printWindow.print();
  };
  const totals = invoices.reduce((sum, item) => sum + Number(item.amount || 0), 0);
  const paid = invoices.filter((item) => item.status === 'Paid').reduce((sum, item) => sum + Number(item.amount || 0), 0);
  return <section className="page">
    <div className="page-heading"><div><p className="eyebrow">REVENUE WORKSPACE</p><h1>Invoices</h1><p className="muted">Create, monitor, and share polished client receipts.</p></div><button className="primary-button compact-button" onClick={() => { resetForm(); setInvoiceModalOpen(true); }}><AddRounded fontSize="small" /> New invoice</button></div>
    <div className="metric-grid invoice-metrics"><article className="metric-card"><span className="metric-icon purple">↗</span><p className="muted">Total billed</p><strong>{money(totals)}</strong><small>{invoices.length} invoices recorded</small></article><article className="metric-card"><span className="metric-icon green">✓</span><p className="muted">Collected</p><strong className="positive">{money(paid)}</strong><small>Paid invoices</small></article><article className="metric-card"><span className="metric-icon amber">◷</span><p className="muted">Awaiting payment</p><strong>{money(totals - paid)}</strong><small>Open balance</small></article></div>
    <article className="panel invoice-list"><div className="panel-heading"><div><h2>Invoice register</h2><p className="muted">View receipts, print records, or download them for your files.</p></div><span className="status-pill">{invoices.length} total</span></div><div className="table-wrap"><table><thead><tr><th>Invoice</th><th>Client</th><th>Due date</th><th>Amount</th><th>Status</th><th>Actions</th></tr></thead><tbody>{invoices.map((invoice) => <tr key={invoice.id}><td><strong>{invoice.number}</strong><small>Ledgerwise invoice</small></td><td>{invoice.client}</td><td>{invoice.dueDate}</td><td><strong>{money(invoice.amount)}</strong></td><td><span className={`status-pill status-${invoice.status.toLowerCase()}`}>{invoice.status}</span></td><td className="actions invoice-actions"><Tooltip title="View receipt"><IconButton className="table-icon-button" aria-label={`View receipt ${invoice.number}`} onClick={() => setSelected(invoice)}><VisibilityRounded fontSize="small" /></IconButton></Tooltip><Tooltip title="Edit invoice"><IconButton className="table-icon-button" aria-label={`Edit ${invoice.number}`} onClick={() => edit(invoice)}><EditRounded fontSize="small" /></IconButton></Tooltip><Tooltip title="Delete invoice"><IconButton className="table-icon-button danger-icon-button" aria-label={`Delete ${invoice.number}`} onClick={() => deleteInvoice(invoice.id)}><DeleteOutlineRounded fontSize="small" /></IconButton></Tooltip></td></tr>)}</tbody></table></div></article>
    {invoiceModalOpen && <div className="receipt-backdrop" role="presentation" onClick={closeInvoiceModal}><article className="invoice-dialog" role="dialog" aria-modal="true" aria-label={editing ? 'Edit invoice' : 'Create invoice'} onClick={(event) => event.stopPropagation()}><div className="transaction-dialog-header"><div><p className="eyebrow">REVENUE WORKSPACE</p><h2>{editing ? 'Edit invoice' : 'Create an invoice'}</h2><p className="muted">Keep client billing details clear and complete.</p></div><IconButton aria-label="Close invoice form" onClick={closeInvoiceModal}><CloseRounded /></IconButton></div><form className="data-form invoice-form" onSubmit={submit}><label>Invoice number<input name="number" value={form.number} onChange={change} placeholder="INV-1003" required /></label><label>Client<input name="client" value={form.client} onChange={change} placeholder="Client or company" required /></label><label>Due date<input name="dueDate" type="date" value={form.dueDate} onChange={change} required /></label><label>Amount (CAD)<input name="amount" type="number" min="0.01" step="0.01" value={form.amount} onChange={change} required /></label><label>Status<select name="status" value={form.status} onChange={change}><option>Draft</option><option>Sent</option><option>Paid</option><option>Overdue</option></select></label><div className="invoice-form-actions"><button className="secondary-button" type="button" onClick={closeInvoiceModal}>Cancel</button><button className="primary-button compact-button" type="submit">{editing ? 'Save invoice' : 'Create invoice'}</button></div></form></article></div>}
    {selected && <div className="receipt-backdrop" role="presentation" onClick={() => setSelected(null)}><article className="receipt-dialog" role="dialog" aria-modal="true" aria-label="Generated receipt" onClick={(event) => event.stopPropagation()}><div className="receipt-dialog-heading"><div><p className="eyebrow">GENERATED RECEIPT</p><h2>{selected.number}</h2></div><button className="icon-close" onClick={() => setSelected(null)} aria-label="Close receipt">×</button></div><div className="receipt-paper"><div className="receipt-brand"><strong>{settings.businessName}</strong><span>Payment receipt</span></div><div className="receipt-meta"><span>Client<strong>{selected.client}</strong></span><span>Date<strong>{selected.dueDate || '—'}</strong></span></div><div className="receipt-line"><span>Invoice amount</span><strong>{money(selected.amount)}</strong></div><div className="receipt-line"><span>Status</span><span className={`status-pill status-${selected.status.toLowerCase()}`}>{selected.status}</span></div><div className="receipt-total"><span>Total</span><strong>{money(selected.amount)}</strong></div></div><div className="receipt-actions"><button className="secondary-button" onClick={() => printReceipt(selected)}>Print receipt</button><button className="primary-button" onClick={() => downloadReceipt(selected)}>Download receipt</button></div></article></div>}
  </section>;
}
